feat: cert check compare modulus with key file

diff --git a/keyser b/keyser
--- a/keyser
+++ b/keyser
@@ -343,7 +343,8 @@ cert_check(){
   local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
   local cert_file=$fqdn_dir/cert.pem
   local cacert_file=$fqdn_dir/ca.crt
-  cert_check_from_file $cert_file $cacert_file
+  local key_file=$fqdn_dir/key.pem
+  cert_check_from_file $cert_file $cacert_file $key_file
 }
 
 help_cert_check_from_file(){
@@ -354,7 +355,7 @@ Description
   vault.
 
 Usage
-  keyser cert_check_from_file <cert_file> [<cacert_file>]
+  keyser cert_check_from_file <cert_file> [<cacert_file>] [<key_file>]
 
 Internally, the command localize the certificate inside its store. Then, it call
 the cert_check_from_file command.
@@ -379,13 +380,14 @@ cert_check_from_file(){
   shift $((OPTIND-1))
   if [[ -n "$help" ]]; then help_cert_check_from_file; return 0; fi
   local cert_file=$1
+  local cacert_file=$2
+  local key_file=$3
   # Validation
   if [[ -z "$cert_file" ]]; then echo 'Certificate file path is missing from arguments.'; help_cert_check_from_file; return 1; fi
   if [[ ! -f $cert_file ]]; then echo "Certificate file does not exist: \"$cert_file\"."; return 1; fi
-  local cacert_file=$2
   if [[ -z "$cacert_file" ]]; then
     # Discover the certificate in the local vault
-    local fqdn=`openssl x509 -noout -subject -in  $cert_file | sed -n '/^subject/s/^.*CN\s*=\s*//p'`;
+    local fqdn=`openssl x509 -noout -subject -in $cert_file | sed -n '/^subject/s/^.*CN\s*=\s*//p'`;
     local ca_fqdn=${fqdn#*.}
     local ca_fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $ca_fqdn)
     cacert_file=$ca_fqdn_dir/cert.pem
@@ -395,12 +397,71 @@ cert_check_from_file(){
     $cert_file \
     >/dev/null \
     2>&1
-  if [[ $? == 0 ]]; then
-    echo 'Certificate is valid.'
-  else
-    echo 'Certificate is not valid.'
+  local verifyCode=$?
+  if [[ $verifyCode != 0 ]]; then
+    echo "Verification failed: \`openssl verify\` exit code is $verifyCode."
     return 1
   fi
+  if [[ -n $key_file ]]; then
+    utils_openssl_modulus $key_file $cert_file
+    if [[ $? != 0 ]]; then
+      echo "Verification failed: modulus signature don't match."
+      return 1
+    fi
+  fi
+  echo 'Certificate is valid.'
+}
+
+help_cert_export(){
+  echo """
+# Description
+#   Check a hostname certificate against the certificate authority.
+
+# Usage
+#   keyser cert_check <fqdn> [<cacert_file>]
+
+# Internally, the command localize the certificate inside its store. Then, it call the cert_check_from_file command.
+"""
+}
+cert_export(){
+  init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cert_export; return 0; fi
+  local fqdn=$1
+  local target=$2
+  # Validation
+  if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_cert_export; return 1; fi
+  if [[ ! -d "$target" ]]; then echo 'Target is not a directory.'; help_cert_export; return 1; fi
+  # Work
+  local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
+  local key_file=$fqdn_dir/key.pem
+  local cert_file=$fqdn_dir/cert.pem
+  local cacert_file=$fqdn_dir/ca.crt
+  if [[ -n "$KEYSER_GPG_MODE" ]]; then
+    # key_file+='.gpg'
+    echo key_file $key_file
+    utils_decrypt $fqdn_dir/key.pem.gpg $key_file > /dev/null
+  fi
+  cp -rp $key_file $target/$(utils_reverse $fqdn).key.pem
+  cp -rp $cacert_file $target/$(utils_reverse $fqdn).cert.pem
+  cat $cert_file >> $target/$(utils_reverse $fqdn).cert.pem
+  # if [[ -n "$KEYSER_GPG_MODE" ]]; then
+  #   rm $fqdn_dir/key.pem
+  # fi
 }
 
 help_cert_view(){
@@ -684,6 +745,7 @@ utils_encrypt(){
     echo $source
   elif [[ $KEYSER_GPG_MODE == "symmetric" ]]; then
     if [[ ! -f $source ]]; then echo 'No such file to encrypt.'; exit 1; fi
+    if [[ -f $target ]]; then rm $target; fi
     gpg --batch --passphrase "$KEYSER_GPG_PASSPHRASE" --output $target --symmetric $source
     [[ $? != 0 ]] && echo 'GPG command failed' && return 1
     echo $target
@@ -699,9 +761,22 @@ utils_decrypt(){
     echo $source
   elif [[ $KEYSER_GPG_MODE == "symmetric" ]]; then
     if [[ ! -f $source ]]; then echo 'No such file to decrypt.'; exit 1; fi
+    if [[ -f $target ]]; then rm $target; fi
     gpg --batch --passphrase "$KEYSER_GPG_PASSPHRASE" --output $target --decrypt $source 2>/dev/null
     echo $target
   else
+    return 1
+  fi
+}
+
+utils_openssl_modulus(){
+  # Check if Private key and Certificate match
+  # See https://support.openprovider.eu/hc/en-us/articles/360038204734-What-to-do-when-my-Private-key-and-Certificate-do-not-match
+  local key_file=$1
+  local cert_file=$2
+  local keyModulus=`openssl rsa -modulus -noout -in $key_file`
+  local certModulus=`openssl x509 -modulus -noout -in $cert_file`
+  if [[ $keyModulus != $certModulus ]]; then
     return 1
   fi
 }
@@ -774,6 +849,8 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     cert_check) cert_check "${@:2}"
       ;;
     cert_check_from_file) cert_check_from_file "${@:2}"
+      ;;
+    cert_export) cert_export "${@:2}"
       ;;
     cacert_list) cacert_list "${@:2}"
       ;;
