feat: enable help on all commands

diff --git a/keyser b/keyser
--- a/keyser
+++ b/keyser
@@ -232,7 +232,24 @@ Usage
 }
 cacert_view(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cacert_view; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_cacert_view; return 1; fi
   local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
   openssl x509 -noout -text -fingerprint \
@@ -252,7 +269,24 @@ Generate the certificate and private key for a give hostname. The command combin
 }
 cert(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cert; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_cert; return 1; fi
   csr_create $fqdn
   csr_sign $fqdn "${@:2}"
@@ -271,7 +305,24 @@ Internally, the command localize the certificate inside its store. Then, it call
 }
 cert_check(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cert_check; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_cert_check; return 1; fi
   local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
   local cert_file=$fqdn_dir/cert.pem
@@ -295,7 +346,24 @@ the cert_check_from_file command.
 }
 cert_check_from_file(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cert_check_from_file; return 0; fi
   local cert_file=$1
+  # Validation
   if [[ -z "$cert_file" ]]; then echo 'Certificate file path is missing from arguments.'; help_cert_check_from_file; return 1; fi
   if [[ ! -f $cert_file ]]; then echo "Certificate file does not exist: \"$cert_file\"."; return 1; fi
   local cacert_file=$2
@@ -332,7 +400,24 @@ Print the detailed information of a Certificate Signing Request (CSR) file.
 }
 cert_view(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cert_view; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_cert_view; return 1; fi
   # tld=${fqdn#*.}
   # hostname=${fqdn%%.*}
@@ -357,7 +442,24 @@ Generate a key and its certificate signing request.
 }
 csr_create(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_csr_create; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_csr_create; return 1; fi
   # domain=`openssl x509 -noout -subject -in $KEYSER_VAULT_DIR/ca.crt.pem | sed -n '/^subject/s/^.*CN=//p'`
   local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
@@ -396,7 +498,24 @@ Generate a certificate for a managed FQDN with an existing CSR. Internally, it c
 }
 csr_sign(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_csr_sign; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_csr_sign; return 1; fi
   local fqdn_dir="$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)"
   local csr_file="$fqdn_dir/cert.csr"
@@ -408,7 +527,7 @@ csr_sign(){
 help_csr_sign_from_file(){
   echo """
 Description
-  Sign a CSR givent its path.
+  Sign a CSR given its path.
 
 Usage
   keyser csr_sign_from_file <csr_file> [<ca_fqdn>]
@@ -418,10 +537,27 @@ Generate a certificate signing request (CSR) for a given file. The Certificate A
 }
 csr_sign_from_file(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_csr_sign_from_file; return 0; fi
   local csr_file=$1
+  local ca_fqdn=$2
+  # Validation
   if [[ ! -f $csr_file ]]; then echo "CSR file does not exist: \"$csr_file\"."; help_csr_sign_from_file; return 1; fi
   local fqdn=`openssl req -noout -subject -in  $csr_file | sed -n '/^subject/s/^.*CN\s*=\s*//p'`;
-  local ca_fqdn=$2
   if [[ -z "$ca_fqdn" ]]; then 
     ca_fqdn=${fqdn#*.}
   fi
@@ -477,7 +613,24 @@ Print the detailed information of a Certificate Signing Request (CSR) stored ins
 }
 csr_view(){
   init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_csr_view; return 0; fi
   local fqdn=$1
+  # Validation
   if [[ -z "$fqdn" ]]; then echo 'FQDN is missing from arguments.'; help_csr_view; return 1; fi
   local fqdn_dir=$KEYSER_VAULT_DIR/$(utils_reverse $fqdn)
   if [[ ! -f "$fqdn_dir/cert.csr" ]]; then echo "CSR file for domain \"$fqdn\" does not exist."; help_csr_view; return 1; fi
@@ -614,7 +767,9 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
       ;;
     csr_sign) csr_sign "${@:2}"
       ;;
-    csr_view) csr_view "${@:2}"
+    csr_sign) csr_sign "${@:2}"
+      ;;
+    csr_sign_from_file) csr_sign_from_file "${@:2}"
       ;;
     init) init "${@:2}"
       ;;
