feat: new cacert list command

diff --git a/keyser b/keyser
--- a/keyser
+++ b/keyser
@@ -179,6 +179,48 @@ cacert(){
   fi
 }
 
+help_cacert_list(){
+  echo """
+Description
+  List the certificate authorities registered in the vault repository.
+
+Usage
+  keyser cacert_list
+"""
+}
+cacert_list(){
+  init
+  # Parse flags
+  local help
+  while getopts ":h" option; do
+    case $option in
+      h)
+        help=1;;
+      \?)
+        echo "Invalid option -$OPTARG"
+        return 1;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        return 1;;
+    esac
+  done
+  shift $((OPTIND-1))
+  if [[ -n "$help" ]]; then help_cacert_list; return 0; fi
+  # Filter all cacerts based an the CA configuration file
+  # Using cat to always get valid exit code, even when no file is found
+  files=`ls $KEYSER_VAULT_DIR/*/ca.cnf 2>/dev/null | cat`
+  if [[ ${#files} == 0 ]]; then
+    echo 'There are no registered certificate autority in this vault.'
+  else
+    for fqdn in $files; do
+      fqdn=`dirname $fqdn`
+      fqdn=`basename $fqdn`
+      fqdn=`utils_reverse $fqdn`
+      echo $fqdn
+    done
+  fi
+}
+
 help_cacert_view(){
   echo """
 Description
@@ -563,6 +605,8 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     cert_check) cert_check "${@:2}"
       ;;
     cert_check_from_file) cert_check_from_file "${@:2}"
+      ;;
+    cacert_list) cacert_list "${@:2}"
       ;;
     cert_view) cert_view "${@:2}"
       ;;
